### ISSUE TITLE
[Bug]: OS-dashboards Docker image 3.0.0 does not work "Cannot find module 'performance-now'" 

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/dashboards-observability#334]
### Describe the bug

When trying to spin up a cluster with Docker, swapping all the images to `image: opensearchstaging/opensearch:3.0.0` should work. Unfortunately, the dashboards image `image: opensearchstaging/opensearch-dashboards:3.0.0` fails. See below for the log output. Looks, like a module is missing that was expected from observabability dashboards. 

### To reproduce

Take sample docker-compose from website then swap in `image: opensearchstaging/opensearch:3.0.0` and `image: opensearchstaging/opensearch-dashboards:3.0.0` for the node and dashboards images. 

### Expected behavior

The cluster should spin up when the version is valid. 

### Additional context

This issue does not happen on 2.5.0 or 2.6.0, just when trying to use an image of main. 

### Relevant log output

```shell
{"type":"log","@timestamp":"2023-03-23T15:19:16Z","tags":["fatal","root"],"pid":1,"message":"Error: Cannot find module 'performance-now'\nRequire stack:\n- /usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/adaptors/notebooks/default_backend.js\n- /usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/adaptors/notebooks/index.js\n- /usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/routes/notebooks/paraRouter.js\n- /usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/routes/index.js\n- /usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/plugin.js\n- /usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/index.js\n- /usr/share/opensearch-dashboards/src/core/server/plugins/plugin.js\n- /usr/share/opensearch-dashboards/src/core/server/plugins/discovery/plugins_discovery.js\n- /usr/share/opensearch-dashboards/src/core/server/plugins/discovery/index.js\n- /usr/share/opensearch-dashboards/src/core/server/plugins/plugins_service.js\n- /usr/share/opensearch-dashboards/src/core/server/plugins/index.js\n- /usr/share/opensearch-dashboards/src/core/server/index.js\n- /usr/share/opensearch-dashboards/src/cli/serve/serve.js\n- /usr/share/opensearch-dashboards/src/cli/cli.js\n- /usr/share/opensearch-dashboards/src/cli/dist.js\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)\n    at Module.Hook._require.Module.require (/usr/share/opensearch-dashboards/node_modules/require-in-the-middle/index.js:61:29)\n    at require (internal/modules/cjs/helpers.js:101:18)\n    at Object.<anonymous> (/usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/adaptors/notebooks/default_backend.ts:6:1)\n    at Module._compile (internal/modules/cjs/loader.js:1085:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)\n    at Module.load (internal/modules/cjs/loader.js:950:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:790:12)\n    at Module.require (internal/modules/cjs/loader.js:974:19)\n    at Module.Hook._require.Module.require (/usr/share/opensearch-dashboards/node_modules/require-in-the-middle/index.js:80:39)\n    at Module.Hook._require.Module.require (/usr/share/opensearch-dashboards/node_modules/require-in-the-middle/index.js:80:39)\n    at Module.Hook._require.Module.require (/usr/share/opensearch-dashboards/node_modules/require-in-the-middle/index.js:80:39)\n    at Module.Hook._require.Module.require (/usr/share/opensearch-dashboards/node_modules/require-in-the-middle/index.js:80:39)\n    at Module.Hook._require.Module.require (/usr/share/opensearch-dashboards/node_modules/require-in-the-middle/index.js:80:39)\n    at require (internal/modules/cjs/helpers.js:101:18)\n    at Object.<anonymous> (/usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/adaptors/notebooks/index.ts:7:1) {\n  code: 'MODULE_NOT_FOUND',\n  requireStack: [\n    '/usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/adaptors/notebooks/default_backend.js',\n    '/usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/adaptors/notebooks/index.js',\n    '/usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/routes/notebooks/paraRouter.js',\n    '/usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/routes/index.js',\n    '/usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/plugin.js',\n    '/usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/index.js',\n    '/usr/share/opensearch-dashboards/src/core/server/plugins/plugin.js',\n    '/usr/share/opensearch-dashboards/src/core/server/plugins/discovery/plugins_discovery.js',\n    '/usr/share/opensearch-dashboards/src/core/server/plugins/discovery/index.js',\n    '/usr/share/opensearch-dashboards/src/core/server/plugins/plugins_service.js',\n    '/usr/share/opensearch-dashboards/src/core/server/plugins/index.js',\n    '/usr/share/opensearch-dashboards/src/core/server/index.js',\n    '/usr/share/opensearch-dashboards/src/cli/serve/serve.js',\n    '/usr/share/opensearch-dashboards/src/cli/cli.js',\n    '/usr/share/opensearch-dashboards/src/cli/dist.js'\n  ]\n}"}

 FATAL  Error: Cannot find module 'performance-now'
Require stack:
- /usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/adaptors/notebooks/default_backend.js
- /usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/adaptors/notebooks/index.js
- /usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/routes/notebooks/paraRouter.js
- /usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/routes/index.js
- /usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/plugin.js
- /usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/index.js
- /usr/share/opensearch-dashboards/src/core/server/plugins/plugin.js
- /usr/share/opensearch-dashboards/src/core/server/plugins/discovery/plugins_discovery.js
- /usr/share/opensearch-dashboards/src/core/server/plugins/discovery/index.js
- /usr/share/opensearch-dashboards/src/core/server/plugins/plugins_service.js
- /usr/share/opensearch-dashboards/src/core/server/plugins/index.js
- /usr/share/opensearch-dashboards/src/core/server/index.js
- /usr/share/opensearch-dashboards/src/cli/serve/serve.js
- /usr/share/opensearch-dashboards/src/cli/cli.js
- /usr/share/opensearch-dashboards/src/cli/dist.js
```

**Comment by bbarani** [comment]
Moving it to observability dashboards repo. Can someone from @opensearch-project/observability @anirudha take a look at this issue?

**Comment by vamsi-amazon** [comment]
@scrawfor99  could you please test it now. we have merged the fix yesterday.

@bbarani  How can we know the timestamp of last published staging docker build?

**Comment by scrawfor99** [comment]
Hi @vamsi-amazon, I just checked and this is the current output:

```
os-docker-opensearch-dashboards-1  | 
os-docker-opensearch-dashboards-1  |  FATAL  Error: Cannot find module 'performance-now'
os-docker-opensearch-dashboards-1  | Require stack:
os-docker-opensearch-dashboards-1  | - /usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/adaptors/notebooks/default_backend.js
os-docker-opensearch-dashboards-1  | - /usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/adaptors/notebooks/index.js
os-docker-opensearch-dashboards-1  | - /usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/routes/notebooks/paraRouter.js
os-docker-opensearch-dashboards-1  | - /usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/routes/index.js
os-docker-opensearch-dashboards-1  | - /usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/plugin.js
os-docker-opensearch-dashboards-1  | - /usr/share/opensearch-dashboards/plugins/observabilityDashboards/server/index.js
os-docker-opensearch-dashboards-1  | - /usr/share/opensearch-dashboards/src/core/server/plugins/plugin.js
os-docker-opensearch-dashboards-1  | - /usr/share/opensearch-dashboards/src/core/server/plugins/discovery/plugins_discovery.js
os-docker-opensearch-dashboards-1  | - /usr/share/opensearch-dashboards/src/core/server/plugins/discovery/index.js
os-docker-opensearch-dashboards-1  | - /usr/share/opensearch-dashboards/src/core/server/plugins/plugins_service.js
os-docker-opensearch-dashboards-1  | - /usr/share/opensearch-dashboards/src/core/server/plugins/index.js
os-docker-opensearch-dashboards-1  | - /usr/share/opensearch-dashboards/src/core/server/index.js
os-docker-opensearch-dashboards-1  | - /usr/share/opensearch-dashboards/src/cli/serve/serve.js
os-docker-opensearch-dashboards-1  | - /usr/share/opensearch-dashboards/src/cli/cli.js
os-docker-opensearch-dashboards-1  | - /usr/share/opensearch-dashboards/src/cli/dist.js
os-docker-opensearch-dashboards-1  | 
os-docker-opensearch-dashboards-1 exited with code 1
```

Looks like there is still something missing from the distribution on staging. You can check this by using the default docker setup on the [documentation page](https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/). You will just need to swap the plain docker-compose with one which reads `opensearchstaging/opensearch:3.0.0` or opensearchstaging/opensearch-dashboards:3.0.0` where appropriate.

**Comment by ps48** [comment]
@scrawfor99 The staging docker image for `opensearch-dashboards:3.0.0` seems to be an old one. It was published [2 months back](https://hub.docker.com/r/opensearchstaging/opensearch-dashboards/tags?page=1&name=3.0.0). 

Need some input from @bbarani here to see when will the next staging publish happen.

**Comment by derek-ho** [comment]
Done
