### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lazarevdmitriy** [opensearch-project/dashboards-observability#944]
**Trying to create a new visualization in the Observability Dashboard returns the error  "Unable to get default timestamp"**

**Steps to reproduce the behavior:**
1. Go to 'Observability=>Dashboards'
2. Click on 'Create Dashboard' name test
3. Open new dashboard 
4. Click on 'Add visualization=>Create new Visualization'
5. See error 'Unable to get default timestamp'

`TypeError: Cannot read properties of undefined (reading 'toastMessage')
    at ToastsApi.addError (https://l0g.invent.us/6182/bundles/core/core.entry.js:15:635096)
    at PPLDataFetcher._callee$ (https://l0g.invent.us/6182/bundles/plugin/observabilityDashboards/observabilityDashboards.chunk.4.js:1:7463)
    at tryCatch (https://l0g.invent.us/6182/bundles/plugin/observabilityDashboards/observabilityDashboards.chunk.3.js:625:70469)
    at Generator.invoke [as _invoke] (https://l0g.invent.us/6182/bundles/plugin/observabilityDashboards/observabilityDashboards.chunk.3.js:625:74485)
    at Generator.next (https://l0g.invent.us/6182/bundles/plugin/observabilityDashboards/observabilityDashboards.chunk.3.js:625:71664)
    at asyncGeneratorStep (https://l0g.invent.us/6182/bundles/plugin/observabilityDashboards/observabilityDashboards.chunk.4.js:1:2978)
    at _next (https://l0g.invent.us/6182/bundles/plugin/observabilityDashboards/observabilityDashboards.chunk.4.js:1:3289)`

**Environment**
 - kubernetes version 1.26.6
 - https://opster.github.io/opensearch-k8s-operator chart version  "2.3.1"
 - OpenSearchCluster version 2.8.0
 - OpenSearch Dashboards version 2.8.0
 - Plugin observabilityDashboards version 2.8.0

**Screenshots**
![image](https://github.com/opensearch-project/dashboards-observability/assets/6905318/b86fc36d-c2e5-4521-86ab-3369a04fb197)
![image](https://github.com/opensearch-project/dashboards-observability/assets/6905318/d3fb6d4c-d284-4290-9a7d-87fa68cab37e)

**Сonfig where I can reproduce that:**
https://github.com/lazarevdmitriy/images/blob/main/opensearch-cluster.yaml

**Comment by derek-ho** [comment]
@lazarevdmitriy this is a known bug, which should be fixed in the upcoming release CC @mengweieric
